version: "3"
services:
  httpd:
    build:
      context: .
    image: quay.io/polargeospatialcenter/warewulf3:latest
    command: ["start_httpd.sh"]
    volumes:
      - data:/data
    ports:
      - "80:80"
volumes:
  data:
